<#
.SYNOPSIS
    Builds the PhoenixDB native library and installs it into the Dart package.

.DESCRIPTION
    Compiles the Rust cdylib and copies it to native/, where the Dart bindings
    look for it. The C header is generated by build.rs into native/include/.

.PARAMETER Debug
    Build the debug profile instead of release.

.PARAMETER Target
    Rust target triple to cross-compile for.

.PARAMETER Toolchain
    Rustup toolchain to use (e.g. stable-x86_64-pc-windows-gnu).

.EXAMPLE
    .\build.ps1
    .\build.ps1 -Debug
    .\build.ps1 -Target x86_64-pc-windows-msvc
#>
[CmdletBinding()]
param(
    [switch]$Debug,
    [string]$Target = '',
    [string]$Toolchain = ''
)

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RustDir   = Join-Path $ScriptDir 'rust'
$NativeDir = Join-Path $ScriptDir 'native'

$Profile     = if ($Debug) { 'debug' } else { 'release' }
$ProfileFlag = if ($Debug) { @() } else { @('--release') }

function Get-LibName {
    param([string]$Triple)
    if ($Triple -like '*windows*' -or $Triple -eq '') { return 'phoenixdb.dll' }
    if ($Triple -like '*apple*') { return 'libphoenixdb.dylib' }
    return 'libphoenixdb.so'
}

New-Item -ItemType Directory -Force -Path $NativeDir | Out-Null

$cargoArgs = @()
if ($Toolchain -ne '') { $cargoArgs += "+$Toolchain" }
$cargoArgs += @('build', '--lib') + $ProfileFlag

if ($Target -ne '') {
    $cargoArgs += @('--target', $Target)
    $outDir = Join-Path $RustDir "target\$Target\$Profile"
    Write-Host ">> building for $Target ($Profile)"
} else {
    $outDir = Join-Path $RustDir "target\$Profile"
    Write-Host ">> building for the host ($Profile)"
}

Push-Location $RustDir
try {
    & cargo @cargoArgs
    if ($LASTEXITCODE -ne 0) { throw "cargo build failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

$libName = Get-LibName -Triple $Target
$src = Join-Path $outDir $libName
if (-not (Test-Path $src)) {
    throw "expected library not found: $src"
}

$destDir = $NativeDir
if ($Target -ne '') {
    $destDir = Join-Path $NativeDir $Target
    New-Item -ItemType Directory -Force -Path $destDir | Out-Null
}
Copy-Item -Force $src (Join-Path $destDir $libName)
Write-Host "   installed -> $(Join-Path $destDir $libName)"

$header = Join-Path $NativeDir 'include\phoenixdb.h'
if (Test-Path $header) {
    Write-Host ">> header: $header"
}

Write-Host '>> done'
