/*
 * PhoenixDB - C ABI
 *
 * THIS FILE IS AUTO-GENERATED BY cbindgen FROM build.rs. DO NOT EDIT BY HAND.
 *
 * Memory ownership rules:
 *   - Every pointer returned by this library is owned by PhoenixDB and MUST be
 *     released with the matching `phoenix_*_free` function.
 *   - Every pointer passed *into* this library is borrowed for the duration of
 *     the call only; the library never retains it.
 */


#ifndef PHOENIXDB_H
#define PHOENIXDB_H

#pragma once

/* Generated with cbindgen:0.27.0 */

/* Generated with cbindgen. Regenerate with `cargo build`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Size of every page in bytes.
 */
#define PAGE_SIZE 4096

/**
 * Size of the fixed page header in bytes.
 */
#define PAGE_HEADER_SIZE 32

/**
 * Bytes consumed by one slot-directory entry.
 */
#define SLOT_SIZE 4

/**
 * Sentinel for "no such page".
 */
#define SENTINEL UINT32_MAX

/**
 * Largest key the engine can store in a page (structural limit).
 *
 * Two keys plus their overhead must always fit in one page so that a split can
 * make progress; 1 KiB keeps the tree fan-out sane.
 */
#define MAX_KEY_SIZE 1024

/**
 * Largest value stored inline in a leaf cell. Anything larger spills into an
 * overflow-page chain.
 */
#define MAX_INLINE_VALUE 1024

/**
 * Payload capacity of a single overflow page.
 */
#define OVERFLOW_PAYLOAD ((PAGE_SIZE - PAGE_HEADER_SIZE) - 8)

/**
 * Usable space for slots + cells on a normal page.
 */
#define USABLE_SPACE (PAGE_SIZE - PAGE_HEADER_SIZE)

/**
 * File magic: `PHOENIXDB` truncated to 8 bytes.
 */
#define MetaData_MAGIC 5784960880442169412

/**
 * Current on-disk format version.
 */
#define MetaData_VERSION 1

/**
 * Default clean-page cache capacity (4 MiB worth of pages).
 */
#define DEFAULT_CACHE_PAGES 1024

/**
 * Maximum key length accepted at the FFI boundary (1 MiB).
 *
 * Note: the *storage engine* imposes a much smaller structural limit
 * ([`crate::page::MAX_KEY_SIZE`]) because keys must be comparable in-page.
 * Keys between the two limits are rejected with `InvalidArgument`, never by
 * dereferencing an oversized buffer.
 */
#define MAX_KEY_LEN (1024 * 1024)

/**
 * Maximum value length accepted at the FFI boundary (10 MiB).
 */
#define MAX_VALUE_LEN ((10 * 1024) * 1024)

/**
 * Stable status codes returned by every `phoenix_*` FFI entry point.
 *
 * `0` means success; every failure is negative so callers can test `< 0`.
 */
enum PhoenixStatus
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    /**
     * Operation completed successfully.
     */
    PHOENIX_STATUS_OK = 0,
    /**
     * Unclassified internal failure.
     */
    PHOENIX_STATUS_ERROR = -1,
    /**
     * A pointer was null, a length exceeded the documented limit, or an
     * argument was otherwise rejected *before* any dereference took place.
     */
    PHOENIX_STATUS_INVALID_ARGUMENT = -2,
    /**
     * The requested key does not exist in the caller's snapshot.
     */
    PHOENIX_STATUS_NOT_FOUND = -3,
    /**
     * A page failed CRC32 verification, or the file header is not PhoenixDB.
     */
    PHOENIX_STATUS_CORRUPTION = -4,
    /**
     * Underlying I/O failure.
     */
    PHOENIX_STATUS_IO = -5,
    /**
     * Write-write conflict under snapshot isolation; retry the transaction.
     */
    PHOENIX_STATUS_CONFLICT = -6,
    /**
     * A Rust panic was caught at the FFI boundary (never unwinds into Dart).
     */
    PHOENIX_STATUS_PANIC = -7,
    /**
     * The supplied transaction id is unknown, finished, or not owned by this handle.
     */
    PHOENIX_STATUS_TXN_NOT_FOUND = -8,
    /**
     * A structural limit was reached (page/value cannot be stored).
     */
    PHOENIX_STATUS_FULL = -9,
};
#ifndef __cplusplus
typedef int32_t PhoenixStatus;
#endif // __cplusplus

#endif  /* PHOENIXDB_H */
