/*
 * PhoenixDB - C ABI
 *
 * THIS FILE IS AUTO-GENERATED BY cbindgen FROM build.rs. DO NOT EDIT BY HAND.
 *
 * Memory ownership rules:
 *   - Every pointer returned by this library is owned by PhoenixDB and MUST be
 *     released with the matching `phoenix_*_free` function.
 *   - Every pointer passed *into* this library is borrowed for the duration of
 *     the call only; the library never retains it.
 */


#ifndef PHOENIXDB_H
#define PHOENIXDB_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Generated with cbindgen. Regenerate with `cargo build`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Size of every page in bytes.
 */
#define PAGE_SIZE 4096

/**
 * Size of the fixed page header in bytes.
 */
#define PAGE_HEADER_SIZE 32

/**
 * Bytes consumed by one slot-directory entry.
 */
#define SLOT_SIZE 4

/**
 * Sentinel for "no such page".
 */
#define SENTINEL UINT32_MAX

/**
 * Largest key the engine can store in a page (structural limit).
 *
 * Two keys plus their overhead must always fit in one page so that a split can
 * make progress; 1 KiB keeps the tree fan-out sane.
 */
#define MAX_KEY_SIZE 1024

/**
 * Largest value stored inline in a leaf cell. Anything larger spills into an
 * overflow-page chain.
 */
#define MAX_INLINE_VALUE 1024

/**
 * Payload capacity of a single overflow page.
 */
#define OVERFLOW_PAYLOAD ((PAGE_SIZE - PAGE_HEADER_SIZE) - 8)

/**
 * Usable space for slots + cells on a normal page.
 */
#define USABLE_SPACE (PAGE_SIZE - PAGE_HEADER_SIZE)

/**
 * File magic: `PHOENIXDB` truncated to 8 bytes.
 */
#define MetaData_MAGIC 5784960880442169412

/**
 * Current on-disk format version.
 */
#define MetaData_VERSION 1

/**
 * Default clean-page cache capacity (4 MiB worth of pages).
 */
#define DEFAULT_CACHE_PAGES 1024

/**
 * Maximum key length accepted at the FFI boundary (1 MiB).
 *
 * Note: the *storage engine* imposes a much smaller structural limit
 * ([`crate::page::MAX_KEY_SIZE`]) because keys must be comparable in-page.
 * Keys between the two limits are rejected with `InvalidArgument`, never by
 * dereferencing an oversized buffer.
 */
#define MAX_KEY_LEN (1024 * 1024)

/**
 * Maximum value length accepted at the FFI boundary (10 MiB).
 */
#define MAX_VALUE_LEN ((10 * 1024) * 1024)

/**
 * Longest identifier accepted, in bytes.
 */
#define MAX_IDENT_LEN 128

/**
 * Stable status codes returned by every `phoenix_*` FFI entry point.
 *
 * `0` means success; every failure is negative so callers can test `< 0`.
 */
enum PhoenixStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Operation completed successfully.
     */
    PHOENIX_STATUS_OK = 0,
    /**
     * Unclassified internal failure.
     */
    PHOENIX_STATUS_ERROR = -1,
    /**
     * A pointer was null, a length exceeded the documented limit, or an
     * argument was otherwise rejected *before* any dereference took place.
     */
    PHOENIX_STATUS_INVALID_ARGUMENT = -2,
    /**
     * The requested key does not exist in the caller's snapshot.
     */
    PHOENIX_STATUS_NOT_FOUND = -3,
    /**
     * A page failed CRC32 verification, or the file header is not PhoenixDB.
     */
    PHOENIX_STATUS_CORRUPTION = -4,
    /**
     * Underlying I/O failure.
     */
    PHOENIX_STATUS_IO = -5,
    /**
     * Write-write conflict under snapshot isolation; retry the transaction.
     */
    PHOENIX_STATUS_CONFLICT = -6,
    /**
     * A Rust panic was caught at the FFI boundary (never unwinds into Dart).
     */
    PHOENIX_STATUS_PANIC = -7,
    /**
     * The supplied transaction id is unknown, finished, or not owned by this handle.
     */
    PHOENIX_STATUS_TXN_NOT_FOUND = -8,
    /**
     * A structural limit was reached (page/value cannot be stored).
     */
    PHOENIX_STATUS_FULL = -9,
    /**
     * The caller stopped an iteration early (a scan callback returned
     * non-zero). Not a failure of the engine.
     */
    PHOENIX_STATUS_ABORTED = -10,
    /**
     * The database file is locked by another process.
     */
    PHOENIX_STATUS_BUSY = -11,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum PhoenixStatus PhoenixStatus;
#else
typedef int32_t PhoenixStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A collection of documents; see the module docs.
 */
typedef struct Collection Collection;

/**
 * The embedded database handle.
 *
 * Cloning is intentionally not provided: the FFI layer owns exactly one
 * `Database` per `PhoenixDB*` and frees it in `phoenix_close`. Share it across
 * threads with an `Arc`.
 */
typedef struct Database Database;

/**
 * A thread-safe embedded vector index.
 */
typedef struct VectorEngine VectorEngine;

/**
 * A 64-bit magic tag embedded in every heap object exposed to C.
 *
 * The tag is verified in constant time on every entry point. A mismatch means
 * the pointer is stale (use-after-free), foreign, or corrupted, and the call
 * is rejected with `InvalidArgument` instead of dereferencing further.
 */
typedef uint64_t HandleTag;
/**
 * "PHNXDB\0\x01" — chosen to be unlikely in freed or uninitialised memory.
 */
#define HandleTag_MAGIC 5784959862366666753

/**
 * Opaque database handle handed to C.
 *
 * The `tag` is the first field so a stale or foreign pointer is caught by the
 * constant-time check in [`PhoenixDbHandle::validate`] before `db` is
 * touched. `db` is one strong reference (`Arc::into_raw`) to an engine that
 * may be shared with other handles for the same file.
 */
typedef struct {
    HandleTag tag;
    const Database *db;
} PhoenixDB;

/**
 * Engine options accepted by [`phoenix_open_ex`].
 *
 * Zero means "engine default" for every numeric field, so a zeroed struct
 * with only `struct_size` set is valid.
 */
typedef struct {
    /**
     * `sizeof(PhoenixOptions)` as the caller was compiled with. Lets later
     * versions append fields without breaking older callers.
     */
    uint32_t struct_size;
    /**
     * `1` fsyncs the WAL on every commit (the default); `0` hands commits to
     * the OS only (survives an app crash, not power loss). `-1` = default.
     */
    int32_t sync_on_commit;
    /**
     * Clean-page cache capacity in pages; `0` = default.
     */
    uint64_t cache_pages;
    /**
     * WAL size that triggers an automatic checkpoint; `0` = default.
     */
    uint64_t checkpoint_bytes;
    /**
     * Non-zero records engine spans (see `phoenix_spans_json`).
     */
    int32_t tracing;
    /**
     * Leaf fill factor before a split, in `(0.5, 1.0]`; `0` = default.
     */
    float fill_factor_max;
} PhoenixOptions;

/**
 * An owned byte buffer returned to the caller.
 *
 * Release it with [`phoenix_buffer_free`]. `ptr` is null when `len` is zero.
 */
typedef struct {
    /**
     * Pointer to `len` bytes owned by PhoenixDB.
     */
    uint8_t *ptr;
    /**
     * Number of valid bytes.
     */
    uintptr_t len;
    /**
     * Allocated capacity; required to reconstruct the `Vec` on free.
     */
    uintptr_t cap;
} PhoenixBuffer;

/**
 * Receives one key/value pair; return `0` to continue, non-zero to stop.
 */
typedef int (*PhoenixScanCallback)(const uint8_t*, uintptr_t, const uint8_t*, uintptr_t);

/**
 * Runtime statistics written by [`phoenix_stats`].
 */
typedef struct {
    /**
     * Pages allocated in the file.
     */
    uint32_t page_count;
    /**
     * Reserved; always zero.
     */
    uint32_t reserved;
    /**
     * Live transactions.
     */
    uint64_t active_txns;
    /**
     * Keys with versions not yet merged into the tree.
     */
    uint64_t pending_keys;
    /**
     * Current WAL size in bytes.
     */
    uint64_t wal_bytes;
    /**
     * Latest commit timestamp.
     */
    uint64_t commit_ts;
    /**
     * Every version at or below this timestamp is in the durable tree.
     */
    uint64_t tree_ts;
    /**
     * Page reads served from memory.
     */
    uint64_t cache_hits;
    /**
     * Page reads that decoded a page from the file.
     */
    uint64_t cache_misses;
} PhoenixStats;

/**
 * Result of [`phoenix_check`].
 */
typedef struct {
    /**
     * Levels from the root to the leaves.
     */
    uint32_t depth;
    /**
     * Leaf pages reachable from the root.
     */
    uint32_t leaf_pages;
    /**
     * Internal pages reachable from the root.
     */
    uint32_t internal_pages;
    /**
     * Overflow pages reachable from leaf cells.
     */
    uint32_t overflow_pages;
    /**
     * Pages on the free list.
     */
    uint32_t free_pages;
    /**
     * Allocated pages neither reachable nor free (leaked by a crash).
     */
    uint32_t unreachable_pages;
    /**
     * Non-root leaves below the minimum fill factor.
     */
    uint32_t underfull_leaves;
    /**
     * Reserved; always zero.
     */
    uint32_t reserved;
    /**
     * Keys stored in the tree (excluding unmerged in-memory versions).
     */
    uint64_t keys;
} PhoenixTreeReport;

/**
 * Opaque collection handle handed to C.
 */
typedef struct {
    HandleTag tag;
    /**
     * One strong reference (`Arc::into_raw`) to a possibly shared collection.
     */
    const Collection *collection;
} PhoenixCollectionHandle;

/**
 * Opaque vector-engine handle handed to C.
 *
 * The `tag` is the first field so a stale or foreign pointer is caught by the
 * constant-time check in [`PhoenixVectorHandle::validate`] before `engine` is
 * touched.
 */
typedef struct {
    HandleTag tag;
    /**
     * One strong reference (`Arc::into_raw`) to a possibly shared engine.
     */
    const VectorEngine *engine;
} PhoenixVectorHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Number of distinct engines currently open through the C ABI (diagnostics).
 */
uintptr_t phoenix_open_engine_count(void);

/**
 * Opens (or creates) a database.
 *
 * `path` must be a NUL-terminated UTF-8 string. On success `*out_handle`
 * receives a handle that must be released with [`phoenix_close`].
 *
 * Opening a path this process already has open returns a new handle to the
 * same engine (options of the later open are ignored); every handle must be
 * closed. A file locked by another process fails with `PHOENIX_STATUS_BUSY`.
 *
 * # Safety
 * `path` must point to a valid NUL-terminated string and `out_handle` to a
 * writable pointer-sized location.
 */
int phoenix_open(const char *path, uintptr_t cache_pages, PhoenixDB **out_handle);

/**
 * Opens (or creates) a database with explicit engine options.
 *
 * `options` may be null for all defaults. See [`phoenix_open`] for sharing
 * and ownership rules.
 *
 * # Safety
 * `path` must point to a valid NUL-terminated string, `options` (if non-null)
 * to a `PhoenixOptions` of at least `options->struct_size` bytes, and
 * `out_handle` to a writable pointer-sized location.
 */
int phoenix_open_ex(const char *path, const PhoenixOptions *options, PhoenixDB **out_handle);

/**
 * Closes a database handle, freeing it.
 *
 * When this is the last handle to its engine, the engine checkpoints and
 * releases the file. Passing the same handle twice is detected by the
 * poisoned tag and reported as `-2` rather than causing a double free.
 *
 * # Safety
 * `handle` must come from [`phoenix_open`] and must not be used afterwards.
 */
int phoenix_close(PhoenixDB *handle);

/**
 * Begins a transaction. `read_only != 0` requests a read-only snapshot.
 *
 * # Safety
 * `handle` must be live and `out_txn` writable.
 */
int phoenix_begin_txn(PhoenixDB *handle, int read_only, uint64_t *out_txn);

/**
 * Commits a transaction, making its writes durable before returning.
 *
 * # Safety
 * `handle` must be live.
 */
int phoenix_commit_txn(PhoenixDB *handle, uint64_t txn_id);

/**
 * Rolls a transaction back, discarding its writes.
 *
 * # Safety
 * `handle` must be live.
 */
int phoenix_rollback_txn(PhoenixDB *handle, uint64_t txn_id);

/**
 * Inserts or replaces a key within `txn_id`.
 *
 * Rejects a null pointer, an empty key, a key over 1 MiB or a value over
 * 10 MiB with `-2` *before* dereferencing anything.
 *
 * # Safety
 * `key`/`value` must each point to at least the stated number of readable
 * bytes for the duration of the call.
 */
int phoenix_insert(PhoenixDB *handle, uint64_t txn_id, const uint8_t *key, uintptr_t key_len, const uint8_t *value, uintptr_t value_len);

/**
 * Reads a key within `txn_id` into a freshly allocated buffer.
 *
 * On success `*out` owns the value and must be released with
 * [`phoenix_buffer_free`]. Returns `-3` when the key is not visible.
 *
 * # Safety
 * `key` must be readable for `key_len` bytes; `out` must be writable.
 */
int phoenix_get(PhoenixDB *handle, uint64_t txn_id, const uint8_t *key, uintptr_t key_len, PhoenixBuffer *out);

/**
 * Deletes a key within `txn_id`. Returns `-3` when the key does not exist.
 *
 * # Safety
 * `key` must be readable for `key_len` bytes.
 */
int phoenix_delete(PhoenixDB *handle, uint64_t txn_id, const uint8_t *key, uintptr_t key_len);

/**
 * Single-call insert in an implicit transaction (begin + insert + commit).
 *
 * # Safety
 * Same buffer requirements as [`phoenix_insert`].
 */
int phoenix_put_auto(PhoenixDB *handle, const uint8_t *key, uintptr_t key_len, const uint8_t *value, uintptr_t value_len);

/**
 * Releases a buffer produced by [`phoenix_get`].
 *
 * Idempotent for a zeroed buffer and safe with a null argument. This is the
 * **only** legal way to release PhoenixDB memory; the host allocator's `free`
 * must never be used.
 *
 * # Safety
 * `buf`, if non-null, must point to a `PhoenixBuffer` this library produced
 * and that has not already been freed.
 */
void phoenix_buffer_free(PhoenixBuffer *buf);

/**
 * Frees a string returned by [`phoenix_last_error`].
 *
 * # Safety
 * `s` must have come from [`phoenix_last_error`] and not been freed already.
 */
void phoenix_string_free(char *s);

/**
 * Returns a NUL-terminated description of this thread's last failure.
 *
 * The caller owns the string and must release it with
 * [`phoenix_string_free`]. Returns null when no error has been recorded.
 */
char *phoenix_last_error(void);

/**
 * Merges pending versions into the tree, flushes and truncates the WAL.
 *
 * # Safety
 * `handle` must be live.
 */
int phoenix_checkpoint(PhoenixDB *handle);

/**
 * Flushes dirty pages and syncs the WAL without truncating it.
 *
 * # Safety
 * `handle` must be live.
 */
int phoenix_flush(PhoenixDB *handle);

/**
 * Verifies every page checksum and the B+Tree ordering invariants.
 *
 * # Safety
 * `handle` must be live.
 */
int phoenix_verify(PhoenixDB *handle);

/**
 * Writes the number of visible keys to `*out_len`.
 *
 * # Safety
 * `handle` must be live and `out_len` writable.
 */
int phoenix_count(PhoenixDB *handle, uint64_t *out_len);

/**
 * ABI version of this build. Dart refuses to load a mismatched library.
 *
 * * 3 (PhoenixDB 2.1): the `phoenix_vector_*` surface was added.
 * * 4 (PhoenixDB 4.0): `phoenix_open_ex`, range/prefix scans, write batches,
 *   backup/restore/compact, stats, structural check, metrics text, tracing,
 *   and the `ABORTED`/`BUSY` status codes. Every earlier entry point keeps
 *   its signature.
 */
uint32_t phoenix_abi_version(void);

/**
 * Whether this build includes the vector search engine.
 *
 * Always true for the current build: the vector engine has no optional
 * dependencies and is compiled unconditionally. The flag exists so a Dart
 * caller can branch on capability rather than on version arithmetic, exactly
 * as it does for [`phoenix_has_sql`].
 */
int phoenix_has_vector(void);

/**
 * Whether this build was compiled with the `sql` feature.
 *
 * Lets a Dart caller degrade gracefully instead of getting an error from a
 * lean embedded build that has no query layer.
 */
int phoenix_has_sql(void);

/**
 * Executes one SQL statement, returning the result as a JSON document.
 *
 * JSON is deliberate: a result set is a ragged, dynamically-typed table, and
 * modelling it as a C struct would mean a second allocation protocol and a
 * matching free function for every shape. One UTF-8 buffer with one owner is
 * far harder to leak.
 *
 * The document is one of:
 *
 * ```json
 * {"type":"rows","columns":["a","b"],"rows":[[1,"x"]]}
 * {"type":"affected","count":3}
 * {"type":"schema","detail":"table `t` created with 2 column(s)"}
 * ```
 *
 * On success `*out_json` receives a NUL-terminated string that the caller
 * must release with [`phoenix_string_free`]. On failure it is set to null and
 * a negative status is returned; the message is available from
 * `phoenix_last_error`.
 *
 * # Safety
 * `handle` must be live, `sql` a NUL-terminated UTF-8 string, and `out_json` a
 * writable pointer-sized location.
 */
int phoenix_sql_query(PhoenixDB *handle, const char *sql, char **out_json);

/**
 * Executes one SQL statement with bound parameters, optionally inside the
 * caller's transaction.
 *
 * * `txn_id == 0` runs the statement in its own transaction (retried
 *   transparently on a write-write conflict). Otherwise it runs inside
 *   `txn_id`, atomically (a failure stages nothing); committing and retrying
 *   on `PHOENIX_STATUS_CONFLICT` are then the caller's.
 * * `params_json` is null or a JSON array of scalars bound to `?` / `?N` in
 *   order: `null`, booleans (as 0/1), numbers and strings. Bind user data
 *   this way rather than splicing it into the SQL text.
 *
 * The result document and its ownership are as for [`phoenix_sql_query`].
 *
 * # Safety
 * `handle` must be live, `sql` (and `params_json` when non-null) NUL-terminated
 * UTF-8 strings, and `out_json` a writable pointer-sized location.
 */
int phoenix_sql_query_params(PhoenixDB *handle, uint64_t txn_id, const char *sql, const char *params_json, char **out_json);

/**
 * Maximum key length accepted by the FFI layer, in bytes.
 */
uintptr_t phoenix_max_key_len(void);

/**
 * Maximum value length accepted by the FFI layer, in bytes.
 */
uintptr_t phoenix_max_value_len(void);

/**
 * Streams every visible key/value pair to `callback`, in key order.
 *
 * The callback receives pointers into Rust-owned memory that are valid only
 * for the duration of that call; it must copy what it keeps and must not
 * free them. It runs while the engine's shared lock is held, so it must not
 * call back into this database. Returning non-zero stops the scan and makes
 * this function return `PHOENIX_STATUS_ABORTED`.
 *
 * # Safety
 * `callback` must be null or valid for the duration of the scan.
 */
int phoenix_scan_iter(PhoenixDB *handle, PhoenixScanCallback callback);

/**
 * Collects key/value pairs with keys between two bounds into one buffer.
 *
 * * `txn_id == 0` reads the latest committed state; otherwise the scan sees
 *   that transaction's snapshot and its own uncommitted writes.
 * * `lo_mode` / `hi_mode`: `0` unbounded (pointer ignored), `1` inclusive,
 *   `2` exclusive.
 * * Stops after `limit` pairs, or once the buffer holds at least `max_bytes`
 *   bytes (each `0` = no limit). To page, call again with the last key as an
 *   exclusive lower bound.
 *
 * `*out` receives repeated `[u32 LE key_len][key][u32 LE value_len][value]`
 * records in ascending key order; release it with [`phoenix_buffer_free`].
 * No callback is involved, so this is safe to call from any thread.
 *
 * # Safety
 * Bound pointers must be readable for their lengths; `out` must be writable.
 */
int phoenix_scan_range(PhoenixDB *handle, uint64_t txn_id, const uint8_t *lo, uintptr_t lo_len, int lo_mode, const uint8_t *hi, uintptr_t hi_len, int hi_mode, uint64_t limit, uint64_t max_bytes, PhoenixBuffer *out);

/**
 * Collects pairs whose key starts with `prefix`; otherwise identical to
 * [`phoenix_scan_range`]. An empty prefix scans everything.
 *
 * # Safety
 * `prefix` must be readable for `prefix_len` bytes; `out` must be writable.
 */
int phoenix_scan_prefix(PhoenixDB *handle, uint64_t txn_id, const uint8_t *prefix, uintptr_t prefix_len, uint64_t limit, uint64_t max_bytes, PhoenixBuffer *out);

/**
 * Applies a batch of writes atomically in one transaction.
 *
 * `ops` holds repeated records: `[u8 op][u32 LE key_len][key]` followed, for
 * a put, by `[u32 LE value_len][value]`. Ops: `1` put, `2` delete (fails the
 * whole batch with `NOT_FOUND` if the key is absent), `3` delete if present.
 * The batch is validated before anything is staged; any failure rolls the
 * whole batch back. Maximum batch size: 1 GiB.
 *
 * # Safety
 * `ops` must be readable for `ops_len` bytes.
 */
int phoenix_write_batch(PhoenixDB *handle, const uint8_t *ops, uintptr_t ops_len);

/**
 * Writes a consistent, compacted, self-contained copy of the database to
 * `path` while other callers keep reading and writing.
 *
 * # Safety
 * `handle` must be live and `path` a NUL-terminated UTF-8 string.
 */
int phoenix_backup(PhoenixDB *handle, const char *path);

/**
 * Replaces the database's contents with the backup at `path`, atomically.
 * Fails with `INVALID_ARGUMENT` while any transaction is open.
 *
 * # Safety
 * `handle` must be live and `path` a NUL-terminated UTF-8 string.
 */
int phoenix_restore(PhoenixDB *handle, const char *path);

/**
 * Rebuilds the file with live data only, returning free pages to the
 * filesystem. Blocks other callers for the duration.
 *
 * # Safety
 * `handle` must be live.
 */
int phoenix_compact(PhoenixDB *handle);

/**
 * Writes runtime statistics to `*out`.
 *
 * # Safety
 * `handle` must be live and `out` writable.
 */
int phoenix_stats(PhoenixDB *handle, PhoenixStats *out);

/**
 * Runs the full structural check and writes its report to `*out`.
 *
 * Returns `PHOENIX_STATUS_CORRUPTION` (with details from
 * `phoenix_last_error`) when any invariant is violated.
 *
 * # Safety
 * `handle` must be live and `out` writable.
 */
int phoenix_check(PhoenixDB *handle, PhoenixTreeReport *out);

/**
 * Renders the metrics registry: `format` `0` = human-readable report, `1` =
 * Prometheus text exposition. `*out` receives a string to release with
 * [`phoenix_string_free`].
 *
 * # Safety
 * `handle` must be live and `out` writable.
 */
int phoenix_metrics_text(PhoenixDB *handle, int format, char **out);

/**
 * Writes the engine's metrics report into `out_buf` as a NUL-terminated UTF-8
 * string.
 *
 * Returns the number of bytes written (excluding the NUL terminator), or a
 * negative [`PhoenixStatus`]: `PHOENIX_STATUS_FULL` when `out_len` is too
 * small (nothing is written). Prefer [`phoenix_metrics_text`], which has no
 * size negotiation.
 *
 * # Safety
 * `handle` must be live, `out_buf` must point to `out_len` writable bytes.
 */
intptr_t phoenix_metrics_report(PhoenixDB *handle, uint8_t *out_buf, uintptr_t out_len);

/**
 * Turns span recording on (`enabled != 0`) or off.
 *
 * # Safety
 * `handle` must be live.
 */
int phoenix_set_tracing(PhoenixDB *handle, int enabled);

/**
 * Writes the recorded spans (oldest first, at most the last 1024) as a JSON
 * array to `*out`; release it with [`phoenix_string_free`]. Each element is
 * `{"name","trace_id","span_id","parent_id","duration_us","error","attributes"}`.
 *
 * # Safety
 * `handle` must be live and `out` writable.
 */
int phoenix_spans_json(PhoenixDB *handle, char **out);

/**
 * Opens (creating if needed) the collection in directory `path`.
 *
 * `options_json` may be null or an object with any of `dim` (0 = no vectors
 * / adopt the existing layout), `metric` (`"cosine"`, `"euclidean"`,
 * `"dot_product"` or 0/1/2), `text_index`, `sync`, `m`, `ef_construction`,
 * `ef_search`. A directory already open in this process is shared.
 *
 * # Safety
 * `path` must be a NUL-terminated string, `options_json` null or one, and
 * `out_handle` writable.
 */
int phoenix_collection_open(const char *path, const char *options_json, PhoenixCollectionHandle **out_handle);

/**
 * Releases a handle; the last handle for a directory closes it cleanly.
 * Null and already-closed handles are ignored.
 *
 * # Safety
 * `handle` must come from [`phoenix_collection_open`] and not be used after.
 */
void phoenix_collection_close(PhoenixCollectionHandle *handle);

/**
 * Inserts or replaces documents atomically; see the module docs for the
 * wire format. `vectors` may be null when `vectors_len` (a float count) is 0.
 *
 * # Safety
 * `docs_json` must be a NUL-terminated string and `vectors` readable for
 * `vectors_len` floats.
 */
int phoenix_collection_upsert(PhoenixCollectionHandle *handle, const char *docs_json, const float *vectors, uintptr_t vectors_len);

/**
 * Deletes documents; `ids_json` is a JSON array of ids. `*out_deleted`
 * (optional) receives how many existed.
 *
 * # Safety
 * `ids_json` must be a NUL-terminated string; `out_deleted` null or writable.
 */
int phoenix_collection_delete(PhoenixCollectionHandle *handle, const char *ids_json, uint64_t *out_deleted);

/**
 * Fetches one document as JSON; `PHOENIX_STATUS_NOT_FOUND` when absent.
 *
 * # Safety
 * `id` must be a NUL-terminated string and `out_json` writable.
 */
int phoenix_collection_get(PhoenixCollectionHandle *handle, const char *id, int with_vector, char **out_json);

/**
 * Runs a search. `request_json` is a request object (null = `{}`); the
 * query vector is optional (`query_len == 0`). `*out_json` receives a JSON
 * array of hits `{"id", "score", "vector_score"?, "distance"?,
 * "text_score"?, "text"?, "metadata"?, "vector"?}`.
 *
 * # Safety
 * `request_json` null or NUL-terminated; `query` readable for `query_len`
 * floats; `out_json` writable.
 */
int phoenix_collection_search(PhoenixCollectionHandle *handle, const char *request_json, const float *query, uintptr_t query_len, char **out_json);

/**
 * Counts documents matching `filter_json` (null = all).
 *
 * # Safety
 * `filter_json` null or NUL-terminated; `out_count` writable.
 */
int phoenix_collection_count(PhoenixCollectionHandle *handle, const char *filter_json, uint64_t *out_count);

/**
 * Lists documents matching `filter_json` (null = all) in id order, after
 * `after` (null = from the start), at most `limit` (0 = all), as a JSON
 * array. Vectors are not included.
 *
 * # Safety
 * `filter_json` and `after` null or NUL-terminated; `out_json` writable.
 */
int phoenix_collection_list(PhoenixCollectionHandle *handle, const char *filter_json, uint64_t limit, const char *after, char **out_json);

/**
 * Writes collection statistics as a JSON object
 * `{"documents", "text_documents", "vectors", "dim", "repaired", "metric"}`.
 *
 * # Safety
 * `out_json` must be writable.
 */
int phoenix_collection_stats(PhoenixCollectionHandle *handle, char **out_json);

/**
 * Syncs vectors and checkpoints documents.
 *
 * # Safety
 * `handle` must be a live collection handle.
 */
int phoenix_collection_flush(PhoenixCollectionHandle *handle);

/**
 * Number of distinct collections open in this process (diagnostics).
 */
uint32_t phoenix_collection_open_count(void);

/**
 * Creates a vector index at `path`, or opens an existing one.
 *
 * * `path` — NUL-terminated UTF-8 file path. The graph snapshot lives beside
 *   it at `<path>.hnsw`.
 * * `dim` — dimensionality, `1..=65536`. Must match an existing file.
 * * `metric` — `0` cosine, `1` euclidean, `2` dot product.
 * * `max_elements` — capacity hint used to pre-reserve the id map; `0` means
 *   "unknown", and the index still grows without bound.
 *
 * On success `*out_handle` receives a handle that must be released with
 * [`phoenix_vector_free`]. On failure it is set to null.
 *
 * # Safety
 * `path` must be a valid NUL-terminated string and `out_handle` a writable
 * pointer-sized location.
 */
int phoenix_vector_init(const char *path, uintptr_t dim, uint8_t metric, uintptr_t max_elements, PhoenixVectorHandle **out_handle);

/**
 * Saves and destroys a vector index, freeing the handle.
 *
 * Passing the same handle twice is caught by the poisoned tag and ignored,
 * rather than causing a double free. Null is a no-op.
 *
 * # Safety
 * `handle` must come from [`phoenix_vector_init`] and must not be used
 * afterwards.
 */
void phoenix_vector_free(PhoenixVectorHandle *handle);

/**
 * Inserts or replaces a vector.
 *
 * `vec_ptr` must point to `vec_len` contiguous `f32`s, and `vec_len` must
 * equal the index's dimensionality. The buffer is read, not retained: it may
 * be freed the moment this returns.
 *
 * Re-inserting an existing id replaces it.
 *
 * # Safety
 * `id` must be a valid NUL-terminated string and `vec_ptr` must be readable
 * for `vec_len` floats for the duration of the call.
 */
int phoenix_vector_insert(PhoenixVectorHandle *handle, const char *id, const float *vec_ptr, uintptr_t vec_len);

/**
 * Searches for the `k` nearest neighbours of `query_ptr`.
 *
 * The caller owns both output arrays and must size each to hold at least `k`
 * elements:
 *
 * * `out_ids` receives `*out_count` NUL-terminated strings allocated by this
 *   library. Release the whole array with [`phoenix_free_string_array`],
 *   passing the same count.
 * * `out_scores` receives the matching distances, ascending (nearest first).
 *
 * `*out_count` is set to the number of results actually written, which is at
 * most `k` and may be fewer when the index holds fewer live vectors. It is
 * written before anything else can fail, so it is always meaningful.
 *
 * `ef` overrides the search beam width; `0` selects the configured default.
 * Higher values trade latency for recall.
 *
 * # Safety
 * `query_ptr` must be readable for `query_len` floats; `out_ids` and
 * `out_scores` must each be writable for `k` elements; `out_count` must be
 * writable.
 */
int phoenix_vector_search(const PhoenixVectorHandle *handle, const float *query_ptr, uintptr_t query_len, uintptr_t k, uintptr_t ef, char **out_ids, float *out_scores, uintptr_t *out_count);

/**
 * Inserts (or replaces) `n` vectors in one call and one lock acquisition.
 *
 * `ids` holds `n` NUL-terminated ids; `vectors` holds the vectors back to
 * back (`n * dim` floats). The whole batch is validated before anything is
 * written, so a bad id or vector leaves the index untouched.
 *
 * # Safety
 * `ids` must hold `n` valid NUL-terminated strings and `vectors` must be
 * readable for `n * dim` floats.
 */
int phoenix_vector_insert_batch(const PhoenixVectorHandle *handle, const char *const *ids, uintptr_t n, const float *vectors, uintptr_t dim);

/**
 * Exact `k`-nearest search restricted to the ids in `ids[0..n_ids]` —
 * typically the result of a metadata filter. Unknown or removed ids are
 * ignored. Outputs follow [`phoenix_vector_search`].
 *
 * # Safety
 * As [`phoenix_vector_search`]; additionally `ids` must hold `n_ids` valid
 * NUL-terminated strings.
 */
int phoenix_vector_search_ids(const PhoenixVectorHandle *handle, const float *query_ptr, uintptr_t query_len, uintptr_t k, uintptr_t ef, const char *const *ids, uintptr_t n_ids, char **out_ids, float *out_scores, uintptr_t *out_count);

/**
 * Runs `n_queries` searches in one call. `queries` holds the queries back to
 * back (`n_queries * dim` floats). Query `i` writes up to `k` results at
 * `out_ids[i * k..]` / `out_scores[i * k..]` and its count at
 * `out_counts[i]`. Free each query's ids with [`phoenix_free_string_array`]
 * using its own count.
 *
 * # Safety
 * `queries` must be readable for `n_queries * dim` floats; `out_ids` and
 * `out_scores` writable for `n_queries * k` elements; `out_counts` for
 * `n_queries`.
 */
int phoenix_vector_search_batch(const PhoenixVectorHandle *handle, const float *queries, uintptr_t n_queries, uintptr_t dim, uintptr_t k, uintptr_t ef, char **out_ids, float *out_scores, uintptr_t *out_counts);

/**
 * Fetches a stored vector by id, copying it into `out_vec`.
 *
 * `out_vec` must be writable for `out_len` floats, and `out_len` must equal
 * the index's dimensionality. Returns `-3` when the id is unknown or has been
 * removed.
 *
 * # Safety
 * `id` must be a valid NUL-terminated string; `out_vec` must be writable for
 * `out_len` floats.
 */
int phoenix_vector_get(const PhoenixVectorHandle *handle, const char *id, float *out_vec, uintptr_t out_len);

/**
 * Removes a vector by id. Returns `-3` when it is absent.
 *
 * # Safety
 * `id` must be a valid NUL-terminated string.
 */
int phoenix_vector_remove(PhoenixVectorHandle *handle, const char *id);

/**
 * Writes `1` to `*out_present` when `id` is stored and live, `0` otherwise.
 *
 * # Safety
 * `id` must be a valid NUL-terminated string; `out_present` must be writable.
 */
int phoenix_vector_contains(const PhoenixVectorHandle *handle, const char *id, int *out_present);

/**
 * Syncs the vector file and writes the HNSW snapshot.
 *
 * `path` overrides the snapshot location; pass null for the default
 * `<vector file>.hnsw`. The write is atomic — a temporary file is `fsync`ed
 * and then renamed — so a crash mid-save leaves the previous snapshot intact.
 *
 * # Safety
 * `handle` must be live; `path`, when non-null, must be a valid
 * NUL-terminated string.
 */
int phoenix_vector_save(PhoenixVectorHandle *handle, const char *path);

/**
 * Syncs the vector file without writing a snapshot.
 *
 * # Safety
 * `handle` must be live.
 */
int phoenix_vector_flush(PhoenixVectorHandle *handle);

/**
 * Rewrites the index without tombstoned records, writing the number of
 * reclaimed slots to `*out_reclaimed`.
 *
 * # Safety
 * `handle` must be live; `out_reclaimed`, when non-null, must be writable.
 */
int phoenix_vector_compact(PhoenixVectorHandle *handle, uintptr_t *out_reclaimed);

/**
 * Writes the number of live vectors to `*out_len`.
 *
 * # Safety
 * `handle` must be live and `out_len` writable.
 */
int phoenix_vector_count(const PhoenixVectorHandle *handle, uintptr_t *out_len);

/**
 * Writes the index's dimensionality to `*out_dim`.
 *
 * # Safety
 * `handle` must be live and `out_dim` writable.
 */
int phoenix_vector_dim(const PhoenixVectorHandle *handle, uintptr_t *out_dim);

/**
 * Writes live, total and deleted record counts to the three outputs.
 *
 * Any output may be null, in which case that statistic is skipped.
 *
 * # Safety
 * `handle` must be live; each non-null output must be writable.
 */
int phoenix_vector_stats(const PhoenixVectorHandle *handle, uintptr_t *out_live, uintptr_t *out_total, uintptr_t *out_deleted);

/**
 * Returns a NUL-terminated description of this thread's last vector failure.
 *
 * The caller owns the string and must release it with `phoenix_string_free`.
 * Returns null when no error has been recorded.
 */
char *phoenix_vector_last_error(void);

/**
 * Name of the SIMD kernel this CPU selected: `avx2+fma`, `neon` or
 * `portable`.
 *
 * The returned pointer is a `'static` string owned by the library and must
 * **not** be freed.
 */
const char *phoenix_vector_kernel(void);

/**
 * Largest dimensionality this build accepts.
 */
uintptr_t phoenix_vector_max_dim(void);

/**
 * Largest `k` a single search may request.
 */
uintptr_t phoenix_vector_max_k(void);

/**
 * Largest vector id this build accepts, in bytes.
 */
uintptr_t phoenix_vector_max_id_len(void);

/**
 * Releases an array of `len` strings produced by [`phoenix_vector_search`].
 *
 * Frees each string and then nulls its slot, so a double free is a no-op
 * rather than undefined behaviour. The array itself belongs to the caller and
 * is **not** freed here — only the strings inside it. Null is a no-op.
 *
 * # Safety
 * `ptrs` must point to `len` pointers that this library produced and that have
 * not already been freed.
 */
void phoenix_free_string_array(char **ptrs, uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PHOENIXDB_H */
